stages:
  - dependencies
  - lint
  - test
  - build

image: node:14.3.0-stretch

cache:
  paths:
    - node_modules

install_dependencies:
  stage: dependencies
  script:
    - npm install
    - npm update

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint

integration_test:
  stage: test
  variables:
    DISPLAY: ':99.0'
  before_script:
    - apt-get update
    - apt-get install -y xvfb libxtst6 libnss3 libgtk-3-0 libxss1 libasound2 libsecret-1-0
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm run webpack
  script:
    - npm run test

build:
  stage: build
  artifacts:
    paths:
      - '*.vsix'
    expire_in: 1 year
  script:
    - npx vsce package --baseContentUrl=https://gitlab.com/altom/altwalker/extensions/vscode-model-visualizer/-/raw/master
  only:
    - master
